In [ ]:
import numpy as np
#creating an array
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
#creating an array
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)
z=np.zeros((3,3),dtype=float)
print(z)
o=np.ones((3,3),dtype=int)
print(o)
arange_arr=np.arange(10)
print(arange_arr)
#Array manipulation
arr = np.array([1,2,3,4,5],dtype=float)
reshape_arr=arr.reshape(5,1)
print(reshape_arr)
slice=arr[2:4]
print(slice)
a=np.array([1,2,3,4,5,6,7,8])
trans=a.T
print(trans)
b=np.split(a,4)
print(b)
a=np.array([[1,2],[3,4]])
b=np.array([[5,8],[3,9]])
c=np.dot(a,b)
print(c)
#linalg-linear algebra eig-eigenvalues
d=np.linalg.eig(c)
print(d)
dat=np.loadtxt("/content/drive/MyDrive/dataset/data.txt.txt",dtype=int)
d=np.savetxt("/content/date.txt.txt",dat)
print(d)
print(dat)
a=np.arange(0,1000,10)
print(a)
d=np.savetxt("/content/dat.txt.txt",a)
print(d)
a=np.random.rand()
print(a)
b=np.random.randint(0,2)
print(b)
print(type(a))
a=np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.shape)
m=np.linspace(0.8,3,5)
print(m)
p=np.arange(0,6)
print(p)
n=np.arange(24).reshape(1,4,6)
s=np.arange(24).reshape(2,3,4)
a=np.arange(24).reshape(3,2,4)
print(a)
a=np.array([[1,2],[3,5]])
b=np.array([[3,4],[6,7]])
print(a*b)
print(a@b)
t=np.dot(a,b)
print(t)
a=np.arange(24).reshape(4,2,3)
print(a)

[1. 2. 3. 4. 5.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0 1 2 3 4 5 6 7 8 9]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[[11 26]
 [27 60]]
EigResult(eigenvalues=array([-0.58670115, 71.58670115]), eigenvectors=array([[-0.91340501, -0.3943584 ],
       [ 0.40705196, -0.91895672]]))
None
[[1 2 3]
 [4 5 6]
 [9 8 7]]
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530
 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710
 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890
 900 910 920 930 940 950 960 970 980 990]
None
0.31517417109519164
0
<class 'float'>
<class 'numpy.ndarray'>
2
(2, 2)
[0.8  1.35 1.9  2.45 3.  ]
[0 1 2 3 4 5]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 1

In [ ]:
import numpy as np
a=np.array([[1,2],[3,5]])
b=np.array([[3,4],[6,7]])
print(a*b)

[[ 3  8]
 [18 35]]


In [ ]:
 import numpy as np
 np.arange(1,20)
 #np.arange(1,20,5,dtype=int)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
#linalg-linear algebra eig-eigenvalues
d=np.linalg.eig(c)
print(d)

EigResult(eigenvalues=array([-0.58670115, 71.58670115]), eigenvectors=array([[-0.91340501, -0.3943584 ],
       [ 0.40705196, -0.91895672]]))


In [ ]:
#Array manipulation
arr = np.array([1,2,3,4,5],dtype=float)
reshape_arr=arr.reshape(5,1)
print(reshape_arr)
slice=arr[2:4]
print(slice)
a=np.array([1,2,3,4,5,6,7,8])
trans=a.T
print(trans)
b=np.split(a,4)
print(b)
a=np.array([[1,2],[3,4]])
b=np.array([[5,8],[3,9]])
c=np.dot(a,b)
print(c)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[[11 26]
 [27 60]]


In [ ]:
arange_arr=np.arange(10)
print(arange_arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
z=np.zeros((3,3),dtype=float)
print(z)
o=np.ones((3,3),dtype=int)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[3 3]
[2 2 2]


In [ ]:
from numpy import random
a=np.array([[3,4],[9,6]])
print(a)
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

[[3 4]
 [9 6]]
9
[4 9]
[9 6]
3
[3 6]
[3 4]


In [ ]:
a=np.array([[3,4],[9,6]])
print(a)
print(a.cumsum())
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))


[[3 4]
 [9 6]]
[ 3  7 16 22]
[[ 3  7]
 [ 9 15]]
[[ 3  4]
 [12 10]]


In [ ]:
a=np.array([2,3,5,6])
print(a)
print(a.cumsum())

[2 3 5 6]
[ 2  5 10 16]


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)
b=a.resize(3,2)
print(a)
print(a.shape)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
None


In [ ]:
import numpy as np
a=np.array([1,2,3,7,8,9])
x=a.resize(2,3)
b=np.array([9,8,7,6,5,3])
y=b.resize(2,3)
z=np.vstack((a,b))
print(a)
print(z)
print(z.shape)
print(np.dstack((a,b)))


[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]
 [9 8 7]
 [6 5 3]]
(4, 3)
[[[1 9]
  [2 8]
  [3 7]]

 [[7 6]
  [8 5]
  [9 3]]]


In [ ]:
5/3

1.6666666666666667

In [ ]:
n=8
print(type(n))

<class 'int'>


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


no. of rows become columns
no. of columns become rows
groups become rows
group become columns

In [ ]:
print(np.dstack(a))

[[[1 7]
  [2 8]
  [3 9]]]


In [ ]:
c=np.random.random((2,2))
a=np.floor(np.random.random((2,12)))
print(a)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.71154016 0.55406165]
 [0.84337802 0.51491546]]


In [ ]:
a=np.ceil(np.random.random((2,12)))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a1=np.eye(4,dtype=int)
print(a1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
#1*2=2+(4*2=8)+(0*1=0)=10.0inner
print(np.inner(x,y))

print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.1,2.3,4.5,6.7,8.9,9.7,6.8])
#round figure
np.rint(a)

array([ 1.,  2.,  4.,  7.,  9., 10.,  7.])

In [ ]:
a=np.array([2,3,5,7,11])
b=np.array([1,4,6,8,9])
np.true_divide(a,b)

array([2.        , 0.75      , 0.83333333, 0.875     , 1.22222222])

In [ ]:
a=np.array([1,1,1,2,2,3,3])
np.unique(a)

array([1, 2, 3])

In [ ]:
a=np.array([[1,8],[3,7]])
b=np.array([[5,6],[7,8]])
np.setdiff1d(a,b)

array([1, 3])

In [ ]:
s=np.sin(0)
print(s)

0.0


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[9,5],[7,7]])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.mod(a,b)
print(c)

[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)

[ 200  441   60  800 1250 1500]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.inner(a,b)
print(c)

4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
#.normal->gaussian distribution
print(x)

[[ 1.65682114  1.44903639 -2.0193243 ]
 [ 1.61016439  0.32122898  1.56509338]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[4 7 8 4 6 9 6 6 6 6]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[0 4 1 3 4 4 1 4 5 3]


In [ ]:
x=random.choice([1,2,6,7,8])
print(x)

1


In [ ]:
from numpy import random
s=random.choice([3,5],p=[0.9,0.1],size=(3,5))
print(s)

[[5 3 3 3 3]
 [3 3 3 3 5]
 [3 3 3 3 3]]


In [ ]:
x=random.normal(loc=1,scale=2,size=(2,3))
#loc->mean
#scale->standard deviation
print(x)

[[ 3.45928994  3.35142479 -0.52675133]
 [-1.77887246 -0.92334165 -0.12126666]]


In [ ]:
a=np.array([[1,7],[3,4]])
b=np.array([[9,5],[7,7]])
np.intersect1d(a,b)

array([7])